sudo: required

services:
 - docker

before_install: true
install: true
before_script: true

script:
    - docker build -t cattery .
    - docker run cattery

deploy:
  provider: pypi
  user: gijzelaerr
  password:
    secure: XlGz3/FEHT+e2B1JSFSiW+UPcZ+mGHHEb94a+f+b/UYxgfW/JiLw3EZOSnr6NBbrpA6aNQhPDxMVlMaqtTuOTWOt9sOly9RXfYe8Wem1WzEMbVj9n4P/f8BtJHE/op2aFVhlVGh5aSwt+H6uC7rHlYinQAGN76d+DdUTNwjh3CE=
