language: python
python:
 - "2.7"
sudo: required
dist: trusty
before_install:
- sudo apt-get update
- sudo apt-get install -yq software-properties-common
- sudo add-apt-repository "deb http://us-central1.gce.clouds.archive.ubuntu.com/ubuntu $(lsb_release -sc) main universe restricted multiverse"
- sudo add-apt-repository -y ppa:radio-astro/main
- sudo apt-get update
- sudo apt-get install -yq casacore2 casarest python-pip python-meqtrees-timba python-pyfits python-numpy python-scipy lofar python-astlib python-purr meqtrees-timba
install:
- sudo /usr/bin/pip install .
- sudo /usr/bin/pip install astro-kittens
- sudo /usr/bin/pip install owlcat astro-tigger
- export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
env:
- MEQTREES_CATTERY_PATH=/usr/local/lib/python2.7/dist-packages/Cattery
script:
- cd test/Batchtest
- /usr/bin/python batch_test.py
deploy:
  provider: pypi
  user: gijzelaerr
  password:
    secure: XlGz3/FEHT+e2B1JSFSiW+UPcZ+mGHHEb94a+f+b/UYxgfW/JiLw3EZOSnr6NBbrpA6aNQhPDxMVlMaqtTuOTWOt9sOly9RXfYe8Wem1WzEMbVj9n4P/f8BtJHE/op2aFVhlVGh5aSwt+H6uC7rHlYinQAGN76d+DdUTNwjh3CE=
